# Generated by Django 4.2.1 on 2023-07-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Accepted', 'Accepted'), ('pending', 'pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=34),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Return', 'Return')], default='Pending', max_length=150),
        ),
    ]
