# Generated by Django 4.2.1 on 2023-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Processing', 'Processing'), ('Return', 'Return')], default='Pending', max_length=150),
        ),
    ]
