# Generated by Django 4.2.1 on 2023-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_orderproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Return', 'Return'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Processing', 'Processing'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
    ]
